version: '3.8'

services:
  frontend:
    build: .
    image: shirleys-food-frontend:latest
    container_name: shirleys-food-frontend-production
    ports:
      - '127.0.0.1:4002:3000'
    env_file:
      - ../../.env
    restart: unless-stopped
