name: Deploy to Staging on Push

on:
  push:
    branches:
      - medusa-works

jobs:
  deploy-staging:
    runs-on: ubuntu-latest

    steps:
      - name: Set up SSH for staging
        run: |
          mkdir -p ~/.ssh
          echo "${{ secrets.SSH_PRIVATE_KEY }}" > ~/.ssh/id_ed25519
          chmod 600 ~/.ssh/id_ed25519
          ssh-keyscan -H ${{ vars.REMOTE_HOST }} >> ~/.ssh/known_hosts

      - name: SSH into staging directory and deploy
        run: |
          ssh -i ~/.ssh/id_ed25519 ${{ vars.REMOTE_USER }}@${{ vars.REMOTE_HOST }} << 'EOF'
            export TERM=xterm
            cd ${{ vars.STAGING_DIR }}
            git reset --hard
            git pull
            make restart-d
          EOF
